In [19]:
import Station_Loader_ts as load

from IPython.display import display_html 

# Example 1: Weather in Bozeman, Montana.

This station is located at a college with an agricultural department -- its record extends back to 1895, and it has over 122 years of data of high quality in that time period. I will search around [45.647256643331126,-111.04060494981753], the latitude and longitude of Bozeman.

This station will be loaded using default filter parameters, which includes:
* printudpate=False : detailed, line-by-line updates are not printed.
* min_days_per_mo=15 : each year in the record must have at least 15 days in EVERY single month (and 12 months). Years which do not have 15 days for every month are not included.
* search_radius=3 : the latitude and longitude around which the Reference point is searched.
* firstyear=1900 : the earliest year which must be present in the record.
* lastbaseyear=1955 : the last year to be used in the baseline period. (The baseline period is the years firstyear to lastbaseyear.)
* basenoyears=30 : the number of years of data required in the baseline period (i.e. there must be 30 years of data between 1900 and 1955)
* min_recent_years=5 : the minimum number of years of data in the last immediate record before the present.
* required_trend_years =25 : the minimum number of complete years of data in the last 30 years.


In [2]:
bzdata=load.LoadStation([45.647256643331126,-111.04060494981753]) #Loading in Bozeman, MT coordinates

Searching closest station among 23 stations within 3.0 degrees of the reference.
Which have data for 2021 and at least as early as 1900.0.
Station ID# USC00241044, called MT BOZEMAN MONTANA STATE UNIV is complete. It's good to use.
This station is 1.0690009151710391 miles from the reference point.


## Review Bozeman Montana station information.
Let's review the station metainformation and the filters used to search for it.

In [8]:
print("Station Meta Information:")
print(bzdata.station_information)
print("Filters used to retrieve the station:")
print(bzdata.station_filters)

Station Meta Information:
Weather Station Name                                      MT BOZEMAN MONTANA STATE UNIV
Station ID                                                                  USC00241044
Earliest year in station record                                                  1895.0
Most recent year in record                                                       2022.0
Number of years in record meeting quality requirements                              122
Station Latitude                                                                45.6622
Station Longitude                                                             -111.0464
Reference Point Latitude                                                      45.647257
Reference Point Longitude                                                   -111.040605
Miles from Reference Point                                                     1.069001
dtype: object
Filters used to retrieve the station:
Reference Point Latitude                  

## Review the Data itself
Take a look at the shape of the data and the first few rows.

self.station_data is a numpy array having loaded all the station's data, a numpy array 
     with these columns: [Year, Month, Day, Day of Year, TMAX, TMIN, TMID]

In [12]:
print(f"Shape of the station weather data for Bozeman is: {bzdata.station_data.shape}")
print(bzdata.station_data[0:10])


Shape of the station weather data for Bozeman is: (44310, 7)
[[1.895e+03 1.000e+00 1.000e+00 1.000e+00 2.696e+01 1.940e+00 1.445e+01]
 [1.895e+03 1.000e+00 2.000e+00 2.000e+00 2.804e+01 3.920e+00 1.598e+01]
 [1.895e+03 1.000e+00 3.000e+00 3.000e+00 6.080e+00 1.940e+00 4.010e+00]
 [1.895e+03 1.000e+00 4.000e+00 4.000e+00 4.298e+01 2.498e+01 3.398e+01]
 [1.895e+03 1.000e+00 5.000e+00 5.000e+00 4.298e+01 2.408e+01 3.353e+01]
 [1.895e+03 1.000e+00 6.000e+00 6.000e+00 2.408e+01 1.796e+01 2.102e+01]
 [1.895e+03 1.000e+00 7.000e+00 7.000e+00 2.102e+01 1.940e+00 1.148e+01]
 [1.895e+03 1.000e+00 8.000e+00 8.000e+00 3.398e+01 6.080e+00 2.003e+01]
 [1.895e+03 1.000e+00 9.000e+00 9.000e+00 4.298e+01 1.094e+01 2.696e+01]
 [1.895e+03 1.000e+00 1.000e+01 1.000e+01 4.298e+01 2.408e+01 3.353e+01]]


# Example 2: Load in data for New York City
Let's try New York.
Unsurprisingly, there are a large number of weather stations in this region, with extensive records. Using the search below, I find one with a record extending back to 1869, with 154 years of complete weather station data.

In [20]:
nycdata=load.LoadStation([40.730610, -73.935242],False) #Loading in New York City data


Searching closest station among 40 stations within 3.0 degrees of the reference.
Which have data for 2021 and at least as early as 1900.0.
Station ID# USW00094728, called NY NEW YORK CNTRL PK TWR is complete. It's good to use.
This station is 3.7777425339078192 miles from the reference point.


In [21]:
nycdata.station_information

Weather Station Name                                      NY NEW YORK CNTRL PK TWR
Station ID                                                             USW00094728
Earliest year in station record                                             1869.0
Most recent year in record                                                  2022.0
Number of years in record meeting quality requirements                         154
Station Latitude                                                           40.7789
Station Longitude                                                         -73.9692
Reference Point Latitude                                                  40.73061
Reference Point Longitude                                               -73.935242
Miles from Reference Point                                                3.777743
dtype: object

# Example 3: Load in data for San Francisco, California
Let's try San Francisco using the same parameters. Surprisingly, there are not good records near San Francisco - the closest one which meets all the default conditions is 40 miles away in Napa. I will let this run so you can see the kind of status output it giives. Then, I will change the earliest year to 1940 and the lastbaseyear to 1980, so you can actually see a weather station in San Francisco.

In [28]:
sfdata1=load.LoadStation([37.755663644,-122.506497974],False) #Trying to load in San Frnacisco coordinate using defeault.


Searching closest station among 20 stations within 3.0 degrees of the reference.
Which have data for 2021 and at least as early as 1900.0.
Flag: Insufficent years to calculate recent trend.
You specified that 25.0 years of data in the last 30 be present to calculate a trend, but only 19 are present.
Station ID# USC00040693, called CA BERKELEY is incomplete. Do not use it.
Flag: Insufficent years to calculate recent trend.
You specified that 25.0 years of data in the last 30 be present to calculate a trend, but only 17 are present.
Flag: Insufficent years before 1955.0 to calculate mean for baseline period.
There are 9 years in the period 1900.0 to 1955.0, but I need 30.0 to set an accurate baseline.
Station ID# USC00047880, called CA SAN RAFAEL CIVIC CTR is incomplete. Do not use it.
Flag: Insufficent years to calculate recent trend.
You specified that 25.0 years of data in the last 30 be present to calculate a trend, but only 23 are present.
Station ID# USC00046826, called CA PETALUMA

In [29]:
sfdata2=load.LoadStation([37.755663644,-122.506497974],False,firstyear=1940,lastbaseyear=1980) #Then, force a change which wil return data.

Searching closest station among 64 stations within 3.0 degrees of the reference.
Which have data for 2021 and at least as early as 1940.0.
Station ID# USW00023272, called CA SAN FRANCISCO DWTN is complete. It's good to use.
This station is 4.465465286365231 miles from the reference point.


## Review the two Weather Stations near San Francisco to see how they compare

In [31]:
print("Weather station found in Napa, CA using default filter parameters:")
print(sfdata1.station_information)
print("Weather station found in San Francisco using altered parameters")
print(sfdata2.station_information)

Weather station found in Napa, CA using default filter parameters:
Weather Station Name                                      CA NAPA STATE HOSPITAL
Station ID                                                           USC00046074
Earliest year in station record                                           1893.0
Most recent year in record                                                2022.0
Number of years in record meeting quality requirements                       111
Station Latitude                                                         38.2778
Station Longitude                                                      -122.2647
Reference Point Latitude                                               37.755664
Reference Point Longitude                                            -122.506498
Miles from Reference Point                                              38.37538
dtype: object
Weather station found in San Francisco using altered parameters
Weather Station Name                         

# Example 4: Atlanta, Georgia
As a last example, I will search for a station narrowly in Atlanta Georgia, by narrowing the lat/lon search radius way down and keeping the requirements for an older weather station (i.e., firstyear=1900). You will see that nothing is found, and that an error is returned telling you to change your search parameters. 

So, then I will relax the search radius and see what I turn up within a larger radius going back a bit further in time. And it finds one, albeit 170 miles away, in North Carolina. 

In [36]:
atldata1=load.LoadStation([33.6639, -84.428],True,search_radius=0.5) #Loading in ATlanta GA data

Searching closest station among 1 stations within 0.5 degrees of the reference.
Which have data for 2021 and at least as early as 1900.0.
Beginning to download https://www.ncei.noaa.gov/data/global-historical-climatology-network-daily/access/USC00096335.csv (7.534769 MB). Please wait while the file is transferred.
Time to download this station data: 4.750325918197632 seconds.
I dropped 1891.0 for having only 2 months of data.
I dropped 1892.0 for having only 8 months of data.
I dropped 1893.0 for having only 8 months of data.
I dropped 1894.0 for having only 8 months of data.
I dropped 1900.0 for having less than 15.0s days in month # 1.0.
I dropped 1900.0 for having less than 15.0s days in month # 2.0.
I dropped 1900.0 for having less than 15.0s days in month # 3.0.
I dropped 1900.0 for having less than 15.0s days in month # 4.0.
I dropped 1900.0 for having less than 15.0s days in month # 5.0.
I dropped 1900.0 for having less than 15.0s days in month # 6.0.
I dropped 1900.0 for having

In [39]:
atldata2=load.LoadStation([33.6639, -84.428],False,firstyear=1890) #Loading in ATlanta GA data

Searching closest station among 8 stations within 3.0 degrees of the reference.
Which have data for 2021 and at least as early as 1890.0.
Flag: Insufficent years to calculate recent trend.
You specified that 25.0 years of data in the last 30 be present to calculate a trend, but only 25 are present.
Flag: Insufficent years before 1955.0 to calculate mean for baseline period.
There are 0 years in the period 1890.0 to 1955.0, but I need 30.0 to set an accurate baseline.
Station ID# USC00316001, called NC MURPHY 4ESE is incomplete. Do not use it.
Flag: Insufficent years to calculate recent trend.
You specified that 25.0 years of data in the last 30 be present to calculate a trend, but only 23 are present.
Flag: Insufficent years before 1955.0 to calculate mean for baseline period.
There are 9 years in the period 1890.0 to 1955.0, but I need 30.0 to set an accurate baseline.
Station ID# USC00313228, called NC FRANKLIN is incomplete. Do not use it.
Station ID# USW00013872, called NC ASHEVILL

In [40]:
atldata2.station_information

Weather Station Name                                      NC ASHEVILLE
Station ID                                                 USW00013872
Earliest year in station record                                 1889.0
Most recent year in record                                      2022.0
Number of years in record meeting quality requirements             128
Station Latitude                                               35.5953
Station Longitude                                             -82.5567
Reference Point Latitude                                       33.6639
Reference Point Longitude                                      -84.428
Miles from Reference Point                                  170.537971
dtype: object